// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/tracker/customers.proto

package tracker

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	response "github.com/mhannig/traak/service/lib/v1/response"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Customer struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Customer) Reset()         { *m = Customer{} }
func (m *Customer) String() string { return proto.CompactTextString(m) }
func (*Customer) ProtoMessage()    {}
func (*Customer) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{0}
}

func (m *Customer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Customer.Unmarshal(m, b)
}
func (m *Customer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Customer.Marshal(b, m, deterministic)
}
func (m *Customer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Customer.Merge(m, src)
}
func (m *Customer) XXX_Size() int {
	return xxx_messageInfo_Customer.Size(m)
}
func (m *Customer) XXX_DiscardUnknown() {
	xxx_messageInfo_Customer.DiscardUnknown(m)
}

var xxx_messageInfo_Customer proto.InternalMessageInfo

func (m *Customer) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Customer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// Customers Service
type GetCustomerRequest struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCustomerRequest) Reset()         { *m = GetCustomerRequest{} }
func (m *GetCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*GetCustomerRequest) ProtoMessage()    {}
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{1}
}

func (m *GetCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerRequest.Unmarshal(m, b)
}
func (m *GetCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerRequest.Marshal(b, m, deterministic)
}
func (m *GetCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerRequest.Merge(m, src)
}
func (m *GetCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_GetCustomerRequest.Size(m)
}
func (m *GetCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerRequest proto.InternalMessageInfo

func (m *GetCustomerRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetCustomerResponse struct {
	Customer             *Customer        `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Status               *response.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *GetCustomerResponse) Reset()         { *m = GetCustomerResponse{} }
func (m *GetCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*GetCustomerResponse) ProtoMessage()    {}
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{2}
}

func (m *GetCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCustomerResponse.Unmarshal(m, b)
}
func (m *GetCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCustomerResponse.Marshal(b, m, deterministic)
}
func (m *GetCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCustomerResponse.Merge(m, src)
}
func (m *GetCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_GetCustomerResponse.Size(m)
}
func (m *GetCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCustomerResponse proto.InternalMessageInfo

func (m *GetCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *GetCustomerResponse) GetStatus() *response.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type ListCustomersRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCustomersRequest) Reset()         { *m = ListCustomersRequest{} }
func (m *ListCustomersRequest) String() string { return proto.CompactTextString(m) }
func (*ListCustomersRequest) ProtoMessage()    {}
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{3}
}

func (m *ListCustomersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCustomersRequest.Unmarshal(m, b)
}
func (m *ListCustomersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCustomersRequest.Marshal(b, m, deterministic)
}
func (m *ListCustomersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCustomersRequest.Merge(m, src)
}
func (m *ListCustomersRequest) XXX_Size() int {
	return xxx_messageInfo_ListCustomersRequest.Size(m)
}
func (m *ListCustomersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCustomersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCustomersRequest proto.InternalMessageInfo

type ListCustomersResponse struct {
	Customers            []*Customer      `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Status               *response.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ListCustomersResponse) Reset()         { *m = ListCustomersResponse{} }
func (m *ListCustomersResponse) String() string { return proto.CompactTextString(m) }
func (*ListCustomersResponse) ProtoMessage()    {}
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{4}
}

func (m *ListCustomersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCustomersResponse.Unmarshal(m, b)
}
func (m *ListCustomersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCustomersResponse.Marshal(b, m, deterministic)
}
func (m *ListCustomersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCustomersResponse.Merge(m, src)
}
func (m *ListCustomersResponse) XXX_Size() int {
	return xxx_messageInfo_ListCustomersResponse.Size(m)
}
func (m *ListCustomersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCustomersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCustomersResponse proto.InternalMessageInfo

func (m *ListCustomersResponse) GetCustomers() []*Customer {
	if m != nil {
		return m.Customers
	}
	return nil
}

func (m *ListCustomersResponse) GetStatus() *response.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type CreateCustomerRequest struct {
	Customer             *Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateCustomerRequest) Reset()         { *m = CreateCustomerRequest{} }
func (m *CreateCustomerRequest) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerRequest) ProtoMessage()    {}
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{5}
}

func (m *CreateCustomerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerRequest.Unmarshal(m, b)
}
func (m *CreateCustomerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerRequest.Marshal(b, m, deterministic)
}
func (m *CreateCustomerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerRequest.Merge(m, src)
}
func (m *CreateCustomerRequest) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerRequest.Size(m)
}
func (m *CreateCustomerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerRequest proto.InternalMessageInfo

func (m *CreateCustomerRequest) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

type CreateCustomerResponse struct {
	Customer             *Customer        `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Status               *response.Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CreateCustomerResponse) Reset()         { *m = CreateCustomerResponse{} }
func (m *CreateCustomerResponse) String() string { return proto.CompactTextString(m) }
func (*CreateCustomerResponse) ProtoMessage()    {}
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_46257b8a9ba2f24c, []int{6}
}

func (m *CreateCustomerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateCustomerResponse.Unmarshal(m, b)
}
func (m *CreateCustomerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateCustomerResponse.Marshal(b, m, deterministic)
}
func (m *CreateCustomerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateCustomerResponse.Merge(m, src)
}
func (m *CreateCustomerResponse) XXX_Size() int {
	return xxx_messageInfo_CreateCustomerResponse.Size(m)
}
func (m *CreateCustomerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateCustomerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateCustomerResponse proto.InternalMessageInfo

func (m *CreateCustomerResponse) GetCustomer() *Customer {
	if m != nil {
		return m.Customer
	}
	return nil
}

func (m *CreateCustomerResponse) GetStatus() *response.Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*Customer)(nil), "traak.v1.tracker.Customer")
	proto.RegisterType((*GetCustomerRequest)(nil), "traak.v1.tracker.GetCustomerRequest")
	proto.RegisterType((*GetCustomerResponse)(nil), "traak.v1.tracker.GetCustomerResponse")
	proto.RegisterType((*ListCustomersRequest)(nil), "traak.v1.tracker.ListCustomersRequest")
	proto.RegisterType((*ListCustomersResponse)(nil), "traak.v1.tracker.ListCustomersResponse")
	proto.RegisterType((*CreateCustomerRequest)(nil), "traak.v1.tracker.CreateCustomerRequest")
	proto.RegisterType((*CreateCustomerResponse)(nil), "traak.v1.tracker.CreateCustomerResponse")
}

func init() { proto.RegisterFile("proto/v1/tracker/customers.proto", fileDescriptor_46257b8a9ba2f24c) }

var fileDescriptor_46257b8a9ba2f24c = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x94, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x86, 0x6f, 0x72, 0x45, 0xf4, 0xc8, 0xf5, 0x96, 0x69, 0x15, 0x9b, 0x45, 0x09, 0x83, 0xad,
	0xae, 0x66, 0x88, 0x85, 0xd2, 0x75, 0x5d, 0x74, 0x53, 0x28, 0xc4, 0x5d, 0xe9, 0x66, 0x12, 0x07,
	0x1d, 0x6c, 0x12, 0x3b, 0x33, 0x71, 0x5d, 0x68, 0x7f, 0x55, 0x7f, 0x5d, 0x61, 0xf2, 0xa1, 0x46,
	0x21, 0xe0, 0xa2, 0xbb, 0xc0, 0x3c, 0xef, 0x99, 0x27, 0x2f, 0x27, 0x01, 0x77, 0x2d, 0x13, 0x9d,
	0xd0, 0x8d, 0x47, 0xb5, 0x64, 0xe1, 0x8a, 0x4b, 0x1a, 0xa6, 0x4a, 0x27, 0x11, 0x97, 0x8a, 0x98,
	0x23, 0x74, 0xa6, 0x25, 0x63, 0x2b, 0xb2, 0xf1, 0x48, 0x4e, 0x38, 0x57, 0x65, 0x46, 0x72, 0xb5,
	0x4e, 0x62, 0xc5, 0xa9, 0xd2, 0x4c, 0xa7, 0x79, 0x02, 0x13, 0x68, 0x4d, 0xf3, 0x21, 0xa8, 0x0b,
	0xb6, 0x98, 0x0f, 0x2c, 0xd7, 0x1a, 0x37, 0x7c, 0x5b, 0xcc, 0x11, 0x82, 0x46, 0xcc, 0x22, 0x3e,
	0xb0, 0x5d, 0x6b, 0xdc, 0xf6, 0xcd, 0x33, 0x1e, 0x02, 0x7a, 0xe4, 0xba, 0x88, 0xf8, 0xfc, 0x3d,
	0xe5, 0x4a, 0x57, 0x93, 0xf8, 0xc3, 0x82, 0xf3, 0x3d, 0x2c, 0xbb, 0x1a, 0xdd, 0x41, 0xab, 0x50,
	0x36, 0x74, 0x67, 0xe2, 0x90, 0xaa, 0x32, 0x29, 0x53, 0x25, 0x8b, 0x3c, 0x68, 0x66, 0xd6, 0xc6,
	0xa5, 0x33, 0xb9, 0xdc, 0xa6, 0x8a, 0xd7, 0x22, 0x33, 0x03, 0xf8, 0x39, 0x88, 0xfb, 0x70, 0xf1,
	0x24, 0x54, 0xa9, 0xa0, 0x72, 0x55, 0xfc, 0x65, 0x41, 0xaf, 0x72, 0x90, 0xcb, 0xdd, 0x43, 0xbb,
	0xec, 0x73, 0x60, 0xb9, 0x7f, 0x6b, 0xec, 0xb6, 0xf0, 0x29, 0x7a, 0xcf, 0xd0, 0x9b, 0x4a, 0xce,
	0x34, 0xaf, 0x56, 0x79, 0x62, 0x45, 0xf8, 0xd3, 0x82, 0x7e, 0x75, 0xe2, 0xaf, 0xb7, 0x3e, 0xf9,
	0xb6, 0xe1, 0x7f, 0x31, 0x69, 0xc6, 0xe5, 0x46, 0x84, 0x1c, 0x71, 0xe8, 0xee, 0x8b, 0xa1, 0xd1,
	0x91, 0xeb, 0x8f, 0x95, 0xe1, 0x8c, 0xeb, 0xc1, 0xcc, 0x03, 0xff, 0x41, 0xaf, 0xd0, 0xd9, 0x59,
	0x39, 0x34, 0x3c, 0x8c, 0x1e, 0x2e, 0xae, 0x73, 0x5d, 0x43, 0x95, 0xd3, 0x03, 0xf8, 0xb7, 0xb7,
	0x35, 0xe8, 0xe6, 0x30, 0x79, 0x6c, 0xdf, 0x9c, 0x51, 0x2d, 0x57, 0xdc, 0xf1, 0xe0, 0xbd, 0xd0,
	0x85, 0xd0, 0xcb, 0x34, 0x20, 0x61, 0x12, 0xd1, 0x68, 0xc9, 0xe2, 0x58, 0x2c, 0xa8, 0x89, 0x53,
	0x95, 0x95, 0x49, 0xdf, 0x44, 0xb0, 0xf3, 0x03, 0x08, 0x9a, 0xe6, 0x2b, 0xbe, 0xfd, 0x09, 0x00,
	0x00, 0xff, 0xff, 0x95, 0xca, 0x49, 0x95, 0x1b, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CustomerServiceClient is the client API for CustomerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CustomerServiceClient interface {
	CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error)
	GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error)
	ListCustomers(ctx context.Context, in *ListCustomersRequest, opts ...grpc.CallOption) (*ListCustomersResponse, error)
}

type customerServiceClient struct {
	cc *grpc.ClientConn
}

func NewCustomerServiceClient(cc *grpc.ClientConn) CustomerServiceClient {
	return &customerServiceClient{cc}
}

func (c *customerServiceClient) CreateCustomer(ctx context.Context, in *CreateCustomerRequest, opts ...grpc.CallOption) (*CreateCustomerResponse, error) {
	out := new(CreateCustomerResponse)
	err := c.cc.Invoke(ctx, "/traak.v1.tracker.CustomerService/CreateCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	out := new(GetCustomerResponse)
	err := c.cc.Invoke(ctx, "/traak.v1.tracker.CustomerService/GetCustomer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customerServiceClient) ListCustomers(ctx context.Context, in *ListCustomersRequest, opts ...grpc.CallOption) (*ListCustomersResponse, error) {
	out := new(ListCustomersResponse)
	err := c.cc.Invoke(ctx, "/traak.v1.tracker.CustomerService/ListCustomers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomerServiceServer is the server API for CustomerService service.
type CustomerServiceServer interface {
	CreateCustomer(context.Context, *CreateCustomerRequest) (*CreateCustomerResponse, error)
	GetCustomer(context.Context, *GetCustomerRequest) (*GetCustomerResponse, error)
	ListCustomers(context.Context, *ListCustomersRequest) (*ListCustomersResponse, error)
}

func RegisterCustomerServiceServer(s *grpc.Server, srv CustomerServiceServer) {
	s.RegisterService(&_CustomerService_serviceDesc, srv)
}

func _CustomerService_CreateCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traak.v1.tracker.CustomerService/CreateCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).CreateCustomer(ctx, req.(*CreateCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_GetCustomer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).GetCustomer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traak.v1.tracker.CustomerService/GetCustomer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).GetCustomer(ctx, req.(*GetCustomerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomerService_ListCustomers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCustomersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomerServiceServer).ListCustomers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traak.v1.tracker.CustomerService/ListCustomers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomerServiceServer).ListCustomers(ctx, req.(*ListCustomersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CustomerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "traak.v1.tracker.CustomerService",
	HandlerType: (*CustomerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCustomer",
			Handler:    _CustomerService_CreateCustomer_Handler,
		},
		{
			MethodName: "GetCustomer",
			Handler:    _CustomerService_GetCustomer_Handler,
		},
		{
			MethodName: "ListCustomers",
			Handler:    _CustomerService_ListCustomers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/v1/tracker/customers.proto",
}
