// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/tracker/projects.proto

package tracker

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Projects
type Project struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CustomerId           uint64   `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_59db7582ffde7855, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetCustomerId() uint64 {
	if m != nil {
		return m.CustomerId
	}
	return 0
}

func init() {
	proto.RegisterType((*Project)(nil), "traak.v1.tracker.Project")
}

func init() { proto.RegisterFile("proto/v1/tracker/projects.proto", fileDescriptor_59db7582ffde7855) }

var fileDescriptor_59db7582ffde7855 = []byte{
	// 173 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x8e, 0x31, 0x0b, 0xc2, 0x30,
	0x14, 0x84, 0x69, 0x2d, 0x8a, 0x11, 0x44, 0x32, 0x75, 0x6b, 0x71, 0xea, 0x94, 0x47, 0xf1, 0x1f,
	0xb8, 0xb9, 0x88, 0x74, 0x74, 0x91, 0x34, 0x09, 0xed, 0xb3, 0xa6, 0x29, 0xaf, 0x69, 0x7e, 0xbf,
	0x10, 0x15, 0xdc, 0x8e, 0xbb, 0x0f, 0xee, 0x63, 0xc5, 0x44, 0xce, 0x3b, 0x08, 0x35, 0x78, 0x92,
	0x6a, 0x30, 0x04, 0x13, 0xb9, 0xa7, 0x51, 0x7e, 0x16, 0x71, 0xe1, 0x07, 0x4f, 0x52, 0x0e, 0x22,
	0xd4, 0xe2, 0x0b, 0x1c, 0xaf, 0x6c, 0x73, 0xfb, 0x30, 0x7c, 0xcf, 0x52, 0xd4, 0x79, 0x52, 0x26,
	0x55, 0xd6, 0xa4, 0xa8, 0x39, 0x67, 0xd9, 0x28, 0xad, 0xc9, 0xd3, 0x32, 0xa9, 0xb6, 0x4d, 0xcc,
	0xbc, 0x60, 0x3b, 0xb5, 0xcc, 0xde, 0x59, 0x43, 0x0f, 0xd4, 0xf9, 0x2a, 0xc2, 0xec, 0x57, 0x5d,
	0xf4, 0xb9, 0xbe, 0x43, 0x87, 0xbe, 0x5f, 0x5a, 0xa1, 0x9c, 0x05, 0xdb, 0xcb, 0x71, 0xc4, 0x0e,
	0xe2, 0x2d, 0xcc, 0x86, 0x02, 0x2a, 0x03, 0x2f, 0x6c, 0xff, 0x1c, 0xdb, 0x75, 0x74, 0x3b, 0xbd,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xa1, 0x26, 0x79, 0xb3, 0xbe, 0x00, 0x00, 0x00,
}
